### PR TITLE
Do not prioritize required

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by philsturgeon** [comment]
I'm not so sure about this. We're fundamentally changing an upstream library, which means we'll be on a divergent fork forever, and that should only be done for a really really good reason. I'm not sure this change is good for better-ajv-errors in general, for regardless of it being a fork or not.

We're essentially removing a feature, and we're doing it because we're trying to apply generic JSON Schema validation to a OAS Parameter Object and it just so happens to have a keyword which looks similar.

```
   parameters:
      - name: alias
        in: path
        type: string
        required: true
        example: 'VERIFY_EMAIL'
```

I see that there's a check for the `error.keyword` which is trying to figure out the type of error that is triggered. 

```
const isXError = x => (error /*: Error */) => error.keyword === x;
export const isRequiredError = isXError('required');
```

That's in utils: https://github.com/stoplightio/better-ajv-errors/blob/633857be5c7a66ddb0d4e1870da4b38dc7f33157/src/utils.js#L20

Why is `error.keyword == "required"` in this instance? 

Is there a way we can make sure error required is only triggered if its a non-empty array instead of entirely removing this check?

**Comment by P0lip** [comment]
> I'm not so sure about this. We're fundamentally changing an upstream library, which means we'll be on a divergent fork forever, and that should only be done for a really really good reason.

Our fork already differs quite a bit, as we don't need the vast majority of code that the upstream library offers.
In fact, certain changes were introduced on purpose since they caused issues in Spectral.

```bash
git diff --stat upstream/master -- src/

 src/__tests__/helpers/create-error-instances.js    |   5 +-
 src/__tests__/helpers/filter-redundant-errors.js   |  45 -----
 src/__tests__/helpers/make-tree.js                 |   4 +-
 src/helpers.js                                     |  26 +--
 src/index.js                                       |  21 +-
 src/json/__fixtures__/scenario-1.json              |   3 -
 src/json/__fixtures__/scenario-2.json              |   4 -
 src/json/__fixtures__/scenario-3.json              |   6 -
 src/json/__fixtures__/scenario-4.json              |  11 --
 src/json/__fixtures__/scenario-5.json              |  10 -
 src/json/__tests__/__snapshots__/index.js.snap     | 215 ---------------------
 src/json/__tests__/index.js                        |  77 --------
 src/json/get-decorated-data-path.js                |  41 ----
 src/json/get-meta-from-path.js                     |  29 ---
 src/json/index.js                                  |   2 -
 src/json/utils.js                                  |  12 --
 src/utils.js                                       |   6 +-
 .../__fixtures__/additionalProperties/schema.json  |   5 +-
 .../__fixtures__/default/data.json                 |  10 +-
 .../__fixtures__/default/schema.json               |   4 +-
 src/validation-errors/__fixtures__/enum/data.json  |   2 +-
 .../__fixtures__/enum/schema.json                  |   5 +-
 .../__tests__/__snapshots__/enum.js.snap           |  81 ++++----
 .../__tests__/__snapshots__/main.js.snap           |  45 +----
 .../__tests__/__snapshots__/required.js.snap       |  12 +-
 src/validation-errors/__tests__/enum.js            |  52 +++--
 src/validation-errors/__tests__/main.js            |  22 ++-
 src/validation-errors/__tests__/required.js        |   7 +-
 src/validation-errors/additional-prop.js           |  19 +-
 src/validation-errors/base.js                      |  59 +++---
 src/validation-errors/default.js                   |  18 +-
 src/validation-errors/enum.js                      |  54 ++----
 src/validation-errors/index.js                     |   1 +
 src/validation-errors/required.js                  |  23 +--
 src/validation-errors/type.js                      |  17 ++
 src/validation-errors/utils.js                     |  24 +++
 36 files changed, 219 insertions(+), 758 deletions(-)
 ```


> I'm not sure this change is good for better-ajv-errors in general, for regardless of it being a fork or not.
> We're essentially removing a feature, and we're doing it because we're trying to apply generic JSON Schema validation to a OAS Parameter Object and it just so happens to have a keyword which looks similar.

IMHO it's a bug. Let me explain why.
It may seem a bit confusing, but `required` in OAS Parameter Object is unrelated here.
Below you can find the errors we pass to `better-ajv-errors`. These are errors generated by `ajv`.

```js
[
  {
    keyword: 'additionalProperties',
    dataPath: '/paths/~1required-actions~1{actionId}/put/parameters/0',
    schemaPath: '#/properties/parameters/items/oneOf/0/additionalProperties',
    params: { additionalProperty: 'type' },
    message: 'should NOT have additional properties'
  },
  {
    keyword: 'additionalProperties',
    dataPath: '/paths/~1required-actions~1{actionId}/put/parameters/1',
    schemaPath: '#/properties/parameters/items/oneOf/0/additionalProperties',
    params: { additionalProperty: 'type' },
    message: 'should NOT have additional properties'
  },
  {
    keyword: 'required',
    dataPath: '/paths/~1required-actions~1{actionId}/put',
    schemaPath: '#/required',
    params: { missingProperty: 'responses' },
    message: "should have required property 'responses'"
  }
]
```
I stripped one irrelevant error error and only pasted the ones that matter.
There are 3 errors - the first two ones are 'children' of that required error due to their placement in the document, while the last one is the mentioned `required` error.
Now, because of [this](https://github.com/stoplightio/better-ajv-errors/blob/master/src/helpers.js#L49) check, these two first errors get removed (ignored) for no particular reason.
I cannot seem to find any justification for that action. I find it as a buggy behavior.
We should never strip these two errors, as they have really nothing to do with the last error.
I suppose that check is some optimization for a certain case, but it breaks others.
If you want, I can try to dive into the repo to see if there is any issue connected to the commit that introduced the code to find out what the reasoning was. Perhaps there is some circumstance we'd like to account for as well.
Either way, I already tried out this code in Spectral and it fixed one tiny issue and no other assertions had to be updated, so I'm really unsure what the point of that condition is, yet I'll double-check.

--
By the way, if you place a random `responses` in that document provided in #1400, you'll see the errors are correctly printed by Spectral. It's because that `required` error is no longer reported by `ajv` and `better-ajv-errors` do not remove them.

**Comment by P0lip** [comment]
https://github.com/atlassian/better-ajv-errors/commit/8fd8d29e01272be0a64eb917e9ef4f46dad01a87 here is the commit that introduced the change

**Comment by mkistler** [comment]
I think I'm in agreement with @P0lip here -- I found several instances of `required` errors that mask essentially unrelated "child" errors when developing/testing #1433.  Perhaps there are situations where the child errors are related and should be masked, but at the moment the filtering is much too aggressive IMHO.

**Comment by philsturgeon** [comment]
Great, ok! Thanks for explaining things and digging in more @P0lip, and I really appreciate the +1 @mkistler, that makes it way easier to approve this PR.

**Review by philsturgeon — APPROVED** [review]

**Pull request merged**
